services:

  client:
    container_name: client
    build:
      context: ./client
    image: client
    restart: unless-stopped
    volumes:
    - ./client/src:/usr/share/nginx/html
    ports:
    - "8080:80"

  server:
    container_name: server
    build:
      context: ./server
    image: server
    restart: unless-stopped
    ports:
    - "5000:5000"