services:

  database:
    container_name: database
    image: postgres:alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
    - pgadmin:/var/lib/pgadmin
    ports:
    - 5050:80
    depends_on: 
    - database
    restart: unless-stopped

  server:
    depends_on: 
    - database
    container_name: server
    build:
      context: ./server
    image: server
    restart: unless-stopped
    volumes:
    - ./server:/app
    env_file: .env
    ports:
    - 3000:3000

  client:
    depends_on:
    - server
    container_name: client
    build:
      context: ./client
    image: client
    restart: unless-stopped
    volumes:
    - ./client/src:/usr/share/nginx/html
    ports:
    - 8080:80

volumes:
  db:
  pgadmin: